In [1]:
import numpy as np
import pandas as pd
import random
import os
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from joblib import dump
from tqdm.notebook import tqdm
from sklearn.model_selection import train_test_split
import itertools
from sklearn.utils import shuffle
from scipy import signal
%matplotlib inline

import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau


from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

from utils.deep import preProcess, smoothLabels, oneHot, applyOneHot, evaluate_set, m2tex, get_model


from utils.visualize import showMe
from utils.augment import apply_augment
from config.default import *


%load_ext autoreload
%autoreload 2


C:\Users\Nemes\anaconda3\envs\tf\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Nemes\anaconda3\envs\tf\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Nemes\anaconda3\envs\tf\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\Nemes\anaconda3\envs\tf\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
def create_labels(X):
    y = []
    for i, r in enumerate(X):
        l = np.ones(X[r].shape[0])*i
        y = y + l.tolist()
    y = np.array(y)
    return y


In [5]:
root_path = 'C:/resources/EMG/'
post_fix = '_1s_cleaned' #'_1s_new' #
classes = settings['classes']
subjects = os.listdir(root_path)
results = {} #dictionary of pandas dataframes
cv_results = {}
for subject in subjects:
    print(f'Cross validating, leaving out subject {subject}')
    pd_result, cv_result = cross_validate(subject)
    results[subject] = pd_result
    cv_results[subject] = cv_result
  

Cross validating, leaving out subject S001
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
200/200 [==============================] - 7s 37ms/step - loss: 0.8667 - categorical_accuracy: 0.6832 - val_loss: 1.5219 - val_categorical_accuracy: 0.2311
Epoch 2/30
200/200 [==============================] - 14s 71ms/step - loss: 0.6602 - categorical_accuracy: 0.8130 - val_loss: 1.4080 - val_categorical_accuracy: 0.2430s: 0.7101  - ETA: 7s - loss: 0.7078 - categori - ETA: 6s - loss: 0 - ETA: 5s - loss: 0.6965 - ca - ETA - ETA: 3s - loss: 0.6796 - cate - ETA: 2s - - ETA: 1s - loss: 0.6665 - categorical_accuracy:  - ETA: 0s - loss: 0.6655 - categorical_ac - ETA: 0s - loss: 0.6627 - categorical_accu
Epoch 3/30
200/200 [==============================] - 8s 42ms/step - loss: 0.5581 - categorical_accuracy: 0.8634 - val_loss: 0.7792 - val_categorical_accuracy: 0.7150s - loss: 0.5603 - categorical_accuracy: 0.86 - ETA: 0s - loss: 0.5600 - categorical_accu - ETA: 0s - loss: 

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S002
57 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
216/216 [==============================] - 15s 70ms/step - loss: 0.7977 - categorical_accuracy: 0.7380 - val_loss: 1.3418 - val_categorical_accuracy: 0.2390
Epoch 2/30
216/216 [==============================] - 14s 63ms/step - loss: 0.5775 - categorical_accuracy: 0.8555 - val_loss: 1.0316 - val_categorical_accuracy: 0.4779
Epoch 3/30
216/216 [==============================] - 9s 44ms/step - loss: 0.5227 - categorical_accuracy: 0.8811 - val_loss: 0.5824 - val_categorical_accuracy: 0.8962
Epoch 4/30
216/216 [==============================] - 14s 64ms/step - loss: 0.4847 - categorical_accuracy: 0.8965 - val_loss: 0.4967 - val_categorical_accuracy: 0.9025
Epoch 5/30
216/216 [==============================] - 14s 63ms/step - loss: 0.4711 - categorical_accuracy: 0.9048 - val_loss: 0.4405 - val_categorical_accuracy: 0.9146
Epoch 6/30
216/216 [==============================] 

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S004
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
203/203 [==============================] - 14s 70ms/step - loss: 0.8319 - categorical_accuracy: 0.7191 - val_loss: 1.5142 - val_categorical_accuracy: 0.2734
Epoch 2/30
203/203 [==============================] - 13s 66ms/step - loss: 0.5842 - categorical_accuracy: 0.8542 - val_loss: 1.2274 - val_categorical_accuracy: 0.4129
Epoch 3/30
203/203 [==============================] - 14s 69ms/step - loss: 0.5200 - categorical_accuracy: 0.8827 - val_loss: 0.6304 - val_categorical_accuracy: 0.8417s: 0.5292 - categorical_ac - ETA: 3s - loss: 0.5276 - cate - ETA: 2s - loss: 0.5251 - categorical_accuracy - ETA: 2s - loss: 0.5254 - categorical_accuracy:  - ETA: 1s - loss: 0.5247 - categorical_accu -
Epoch 4/30
203/203 [==============================] - 14s 68ms/step - loss: 0.4983 - categorical_accuracy: 0.8941 - val_loss: 0.4731 - val_categorical_accuracy: 0.9021
Epoch 5/30
203/20

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S005
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
211/211 [==============================] - 14s 68ms/step - loss: 0.8255 - categorical_accuracy: 0.7137 - val_loss: 1.3385 - val_categorical_accuracy: 0.2311
Epoch 2/30
211/211 [==============================] - 14s 65ms/step - loss: 0.5886 - categorical_accuracy: 0.8538 - val_loss: 1.1634 - val_categorical_accuracy: 0.3975
Epoch 3/30
211/211 [==============================] - 13s 64ms/step - loss: 0.5112 - categorical_accuracy: 0.8892 - val_loss: 0.7075 - val_categorical_accuracy: 0.7671
Epoch 4/30
211/211 [==============================] - 13s 64ms/step - loss: 0.4772 - categorical_accuracy: 0.9025 - val_loss: 0.4551 - val_categorical_accuracy: 0.9252
Epoch 5/30
211/211 [==============================] - 13s 64ms/step - loss: 0.4531 - categorical_accuracy: 0.9124 - val_loss: 0.4554 - val_categorical_accuracy: 0.9056
Epoch 6/30
211/211 [==============================]

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S006
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
209/209 [==============================] - 15s 71ms/step - loss: 0.7597 - categorical_accuracy: 0.7472 - val_loss: 1.2910 - val_categorical_accuracy: 0.3647
Epoch 2/30
209/209 [==============================] - 13s 64ms/step - loss: 0.5501 - categorical_accuracy: 0.8695 - val_loss: 0.8973 - val_categorical_accuracy: 0.8230
Epoch 3/30
209/209 [==============================] - 14s 66ms/step - loss: 0.4911 - categorical_accuracy: 0.8982 - val_loss: 0.5503 - val_categorical_accuracy: 0.9025
Epoch 4/30
209/209 [==============================] - 11s 52ms/step - loss: 0.4649 - categorical_accuracy: 0.9096 - val_loss: 0.4526 - val_categorical_accuracy: 0.9148
Epoch 5/30
209/209 [==============================] - 4s 20ms/step - loss: 0.4502 - categorical_accuracy: 0.9147 - val_loss: 0.4216 - val_categorical_accuracy: 0.9304
Epoch 6/30
209/209 [==============================] 

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S007
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
204/204 [==============================] - 14s 68ms/step - loss: 0.9023 - categorical_accuracy: 0.6772 - val_loss: 1.4419 - val_categorical_accuracy: 0.2449
Epoch 2/30
204/204 [==============================] - 13s 63ms/step - loss: 0.6359 - categorical_accuracy: 0.8306 - val_loss: 1.2101 - val_categorical_accuracy: 0.3859
Epoch 3/30
204/204 [==============================] - 13s 63ms/step - loss: 0.5357 - categorical_accuracy: 0.8747 - val_loss: 0.6734 - val_categorical_accuracy: 0.7918
Epoch 4/30
204/204 [==============================] - 13s 64ms/step - loss: 0.4881 - categorical_accuracy: 0.8961 - val_loss: 0.4728 - val_categorical_accuracy: 0.9031 0.4893 - ca
Epoch 5/30
204/204 [==============================] - 13s 63ms/step - loss: 0.4540 - categorical_accuracy: 0.9121 - val_loss: 0.4603 - val_categorical_accuracy: 0.9155
Epoch 6/30
204/204 [===================

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S008
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
205/205 [==============================] - 14s 70ms/step - loss: 0.8531 - categorical_accuracy: 0.6935 - val_loss: 1.4116 - val_categorical_accuracy: 0.2311
Epoch 2/30
205/205 [==============================] - 14s 66ms/step - loss: 0.6270 - categorical_accuracy: 0.8341 - val_loss: 1.0731 - val_categorical_accuracy: 0.5199
Epoch 3/30
205/205 [==============================] - 14s 66ms/step - loss: 0.5496 - categorical_accuracy: 0.8705 - val_loss: 0.7246 - val_categorical_accuracy: 0.7355
Epoch 4/30
205/205 [==============================] - 13s 66ms/step - loss: 0.5127 - categorical_accuracy: 0.8874 - val_loss: 0.5102 - val_categorical_accuracy: 0.9096
Epoch 5/30
205/205 [==============================] - 14s 66ms/step - loss: 0.4825 - categorical_accuracy: 0.9033 - val_loss: 0.4675 - val_categorical_accuracy: 0.9266
Epoch 6/30
205/205 [==============================]

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S009
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
208/208 [==============================] - 15s 70ms/step - loss: 0.8381 - categorical_accuracy: 0.7062 - val_loss: 1.3755 - val_categorical_accuracy: 0.4669
Epoch 2/30
208/208 [==============================] - 14s 65ms/step - loss: 0.6143 - categorical_accuracy: 0.8443 - val_loss: 1.0486 - val_categorical_accuracy: 0.5719
Epoch 3/30
208/208 [==============================] - 14s 65ms/step - loss: 0.5321 - categorical_accuracy: 0.8834 - val_loss: 0.5954 - val_categorical_accuracy: 0.8623
Epoch 4/30
208/208 [==============================] - 14s 65ms/step - loss: 0.5097 - categorical_accuracy: 0.8913 - val_loss: 0.4651 - val_categorical_accuracy: 0.9120
Epoch 5/30
208/208 [==============================] - 13s 65ms/step - loss: 0.4887 - categorical_accuracy: 0.9009 - val_loss: 0.4635 - val_categorical_accuracy: 0.9130
Epoch 6/30
208/208 [==============================]

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S010
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
199/199 [==============================] - 15s 76ms/step - loss: 0.9019 - categorical_accuracy: 0.6709 - val_loss: 1.5719 - val_categorical_accuracy: 0.2315oss: 0.9652 - categorical_accuracy: 0.63 - ETA: 4s - loss: 0.9637 - categorica - ETA: 2s - loss: 0.9300 - categorical_ - ETA: 1s - loss: 0.9231 - categorical_accu - ETA: 1s - loss: 0.9175 - categorical_accuracy: 0. - ETA: 1s - loss: 0.9156  - ETA: 0s - loss: 0.9035 - categorical_accuracy
Epoch 2/30
199/199 [==============================] - 14s 71ms/step - loss: 0.6785 - categorical_accuracy: 0.8058 - val_loss: 1.4099 - val_categorical_accuracy: 0.28868s - loss: 0.7372 - categorical_accura - ETA - E - ETA: 5s - loss: 0.7100 - cate - ETA: 4s - loss: 0.7058 - categorical_accuracy: 0. - ETA: 4s - loss: 0.7063 - categorical_accuracy - ETA: 4s - loss: 0.7042 - categorica - ETA: 3s - loss: 0.7025 - categorical_ - ETA: 3s

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S011
56 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
216/216 [==============================] - 16s 76ms/step - loss: 0.8837 - categorical_accuracy: 0.6900 - val_loss: 1.3248 - val_categorical_accuracy: 0.245211s - loss: 1.3475 - categorical_accuracy: - ETA: 10s - loss: 1.2712 - categorical_ - ETA: 10s - loss: 1.1641 - cat - ETA: 9s - loss: 1.1059 - categorical_ - ETA: 8s - loss: 1.0 - ETA - ETA: 4s - loss: 0.9516 - categorical_accuracy: 0.65 - ETA: 4s - loss: 0.9502 - categorical_accura - ETA: 4s - loss: 0.9439 - catego - ETA: 1s - loss: 0.9055 - categorical_accura - ETA: 1s -
Epoch 2/30
216/216 [==============================] - 15s 71ms/step - loss: 0.6389 - categorical_accuracy: 0.8294 - val_loss: 1.1561 - val_categorical_accuracy: 0.44492s - loss: 0.6478 - categorical_accura
Epoch 3/30
216/216 [==============================] - 15s 71ms/step - loss: 0.5593 - categorical_accuracy: 0.8693 - val_loss: 0.6181 - val_cat

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S101
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
194/194 [==============================] - 14s 72ms/step - loss: 0.9105 - categorical_accuracy: 0.6573 - val_loss: 1.3538 - val_categorical_accuracy: 0.3059 ETA: 7s - loss: 1.0350 -  - ETA: 4s - loss: 0.9735 - cate - ETA: 3s - loss: 0.9608 - categorical_accu - - ETA: 1s - loss: 0.9 - ETA: 0s - loss: 0.9168 - catego
Epoch 2/30
194/194 [==============================] - 14s 72ms/step - loss: 0.6823 - categorical_accuracy: 0.8054 - val_loss: 1.1204 - val_categorical_accuracy: 0.5992oss: 0.716 - ETA: 5s - loss: 0.709 - ETA: 3s - loss: 0.6994 - categorical_accuracy:  - ETA: 2s - loss: 0.6991 - ca - ETA: 2s - loss: 0.6941 - ca - ETA: 1s - l
Epoch 3/30
194/194 [==============================] - 14s 71ms/step - loss: 0.5915 - categorical_accuracy: 0.8520 - val_loss: 0.6973 - val_categorical_accuracy: 0.8273- ETA: 5s - loss: 0.6031 - categori - ETA: 4s - loss: 0.6019 - categor

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S102
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
197/197 [==============================] - 4s 22ms/step - loss: 0.8645 - categorical_accuracy: 0.6973 - val_loss: 1.4199 - val_categorical_accuracy: 0.2449
Epoch 2/30
197/197 [==============================] - 4s 20ms/step - loss: 0.6496 - categorical_accuracy: 0.8233 - val_loss: 1.0941 - val_categorical_accuracy: 0.5809
Epoch 3/30
197/197 [==============================] - 4s 20ms/step - loss: 0.5489 - categorical_accuracy: 0.8689 - val_loss: 0.6508 - val_categorical_accuracy: 0.8302ETA: 0s - loss: 0.5490 - categorical_accuracy: 0.86
Epoch 4/30
197/197 [==============================] - 4s 20ms/step - loss: 0.4979 - categorical_accuracy: 0.8902 - val_loss: 0.4847 - val_categorical_accuracy: 0.9002
Epoch 5/30
197/197 [==============================] - 4s 20ms/step - loss: 0.4758 - categorical_accuracy: 0.9012 - val_loss: 0.4337 - val_categorical_accuracy: 0.9219
Epoch

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S103
55 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
210/210 [==============================] - 4s 21ms/step - loss: 0.8595 - categorical_accuracy: 0.7023 - val_loss: 1.4047 - val_categorical_accuracy: 0.2551
Epoch 2/30
210/210 [==============================] - 4s 20ms/step - loss: 0.5841 - categorical_accuracy: 0.8560 - val_loss: 1.1415 - val_categorical_accuracy: 0.5324
Epoch 3/30
210/210 [==============================] - 4s 20ms/step - loss: 0.5169 - categorical_accuracy: 0.8872 - val_loss: 0.6819 - val_categorical_accuracy: 0.8158
Epoch 4/30
210/210 [==============================] - 4s 20ms/step - loss: 0.4898 - categorical_accuracy: 0.8974 - val_loss: 0.4986 - val_categorical_accuracy: 0.9001
Epoch 5/30
210/210 [==============================] - 4s 20ms/step - loss: 0.4691 - categorical_accuracy: 0.9095 - val_loss: 0.4469 - val_categorical_accuracy: 0.9280
Epoch 6/30
210/210 [==============================] - 4s

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S104
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
208/208 [==============================] - 5s 23ms/step - loss: 0.8197 - categorical_accuracy: 0.7242 - val_loss: 1.3220 - val_categorical_accuracy: 0.3322
Epoch 2/30
208/208 [==============================] - 4s 20ms/step - loss: 0.5823 - categorical_accuracy: 0.8560 - val_loss: 0.9200 - val_categorical_accuracy: 0.7479
Epoch 3/30
208/208 [==============================] - 4s 20ms/step - loss: 0.5188 - categorical_accuracy: 0.8840 - val_loss: 0.5670 - val_categorical_accuracy: 0.9081ategori
Epoch 4/30
208/208 [==============================] - 4s 20ms/step - loss: 0.4875 - categorical_accuracy: 0.9002 - val_loss: 0.4439 - val_categorical_accuracy: 0.9277
Epoch 5/30
208/208 [==============================] - 4s 20ms/step - loss: 0.4697 - categorical_accuracy: 0.9077 - val_loss: 0.4345 - val_categorical_accuracy: 0.9202
Epoch 6/30
208/208 [=============================

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S105
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
209/209 [==============================] - 4s 21ms/step - loss: 0.8588 - categorical_accuracy: 0.7018 - val_loss: 1.3441 - val_categorical_accuracy: 0.3975los
Epoch 2/30
209/209 [==============================] - 4s 20ms/step - loss: 0.5871 - categorical_accuracy: 0.8539 - val_loss: 1.0366 - val_categorical_accuracy: 0.6532
Epoch 3/30
209/209 [==============================] - 4s 20ms/step - loss: 0.5159 - categorical_accuracy: 0.8835 - val_loss: 0.5988 - val_categorical_accuracy: 0.8953
Epoch 4/30
209/209 [==============================] - 4s 20ms/step - loss: 0.4909 - categorical_accuracy: 0.8954 - val_loss: 0.4557 - val_categorical_accuracy: 0.92270.4943 
Epoch 5/30
209/209 [==============================] - 4s 20ms/step - loss: 0.4603 - categorical_accuracy: 0.9094 - val_loss: 0.4551 - val_categorical_accuracy: 0.9075
Epoch 6/30
209/209 [==========================

  0%|          | 0/58 [00:00<?, ?it/s]

Cross validating, leaving out subject S106
54 sessions loaded for training
58 sessions loaded for validation
Epoch 1/30
205/205 [==============================] - 5s 22ms/step - loss: 0.8821 - categorical_accuracy: 0.6948 - val_loss: 1.2321 - val_categorical_accuracy: 0.3783
Epoch 2/30
205/205 [==============================] - 4s 20ms/step - loss: 0.5981 - categorical_accuracy: 0.8515 - val_loss: 1.0239 - val_categorical_accuracy: 0.6289
Epoch 3/30
205/205 [==============================] - 4s 20ms/step - loss: 0.5097 - categorical_accuracy: 0.8909 - val_loss: 0.6111 - val_categorical_accuracy: 0.8853
Epoch 4/30
205/205 [==============================] - 4s 20ms/step - loss: 0.4783 - categorical_accuracy: 0.9040 - val_loss: 0.4725 - val_categorical_accuracy: 0.9189
Epoch 5/30
205/205 [==============================] - 4s 20ms/step - loss: 0.4602 - categorical_accuracy: 0.9113 - val_loss: 0.4302 - val_categorical_accuracy: 0.9272
Epoch 6/30
205/205 [==============================] - 4s

  0%|          | 0/58 [00:00<?, ?it/s]

In [ ]:
print(results)
final = []
for d in results:
    by_subject = results[d].groupby(['Subject']).mean()
    final.append(by_subject.loc[:,'Accuracy'].tolist())
print(np.array(final))
numpy_result = np.array(final)

In [7]:
commutative = []
for subject in subjects:
    print(subject)
    all = []
    for session in cv_results[subject]:
        #print(session)
        if subject in session:
            #print(cv_results[subject][session])
            temp = cv_results[subject][session]
            
            zeros = np.zeros((4,4), dtype = np.float32)
            zeros[:temp.shape[0], :temp.shape[1]] = temp
            #temp.resize(4,4)
            all.append(zeros)
    all = np.array(all)
    summ = np.sum(all,axis = 0 )
    summ = np.array(summ, dtype = np.int)
    commutative.append(summ)
    print(summ)
    np.savetxt('confusion/CNN/'+subject+'.csv', summ,fmt='%i', delimiter=',')

        
commutative = np.array(commutative)
commutative =np.sum(commutative, axis = 0)
np.savetxt('confusion/CNN/commutative.csv', commutative,fmt='%i', delimiter=',')



S001
[[162   0   0   0]
 [ 13 256   4   0]
 [  0   2 289   0]
 [  2   5   6  92]]
S002
[[21  0  0  0]
 [ 6 61  2  0]
 [ 9  0  3  0]
 [ 2  0  0 46]]
S004
[[241   0   0   2]
 [ 31 193   0   4]
 [ 10   0 213   2]
 [  0   0   0  12]]
S005
[[109   0   3   8]
 [  5 181   2   4]
 [  4   0  38   0]
 [  2   3   0   7]]
S006
[[147   0   0   0]
 [ 42  88   7   4]
 [  2   1 120   0]
 [  4   0   2  15]]
S007
[[154   4   0   1]
 [ 19 223   0   4]
 [ 30   1  42  14]
 [ 38   0   0 124]]
S008
[[141   0   0   0]
 [  0 255   0   3]
 [  0   0 206   1]
 [  5   7   1   8]]
S009
[[197   5   2   0]
 [  5 247   0   0]
 [ 10   3   8   0]
 [  6   0   0   6]]
S010
[[ 97   5   0   0]
 [  1 258  13   7]
 [  0   1 287   0]
 [  0   5   3 202]]
S011
[[  4   0   2   0]
 [  0 120   0   0]
 [  0   0   9   0]
 [  0   0   2  10]]
S101
[[237   0   0   0]
 [  3 262   5   0]
 [  0   0 297   0]
 [  1   0   1 286]]
S102
[[243   0   0   0]
 [  2 192  33   4]
 [  0   0 282   0]
 [  3   6  12 201]]
S103
[[174   3   0   0]
 [  6 11

C:\Users\Nemes\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


In [11]:
np.savetxt("cnn_cross_val.csv", numpy_result, delimiter=",",fmt='%1.2f')


In [4]:
def cross_validate(subject, log = False):
    # use session4 for validation
    subject_to_val = [subject]
    train_sessions = []
    val_sessions = []

    for subject in os.listdir(root_path):
        for session in os.listdir(os.path.join(root_path,subject)):
            val_sessions.append(os.path.join(root_path,subject, session))
            if not subject in subject_to_val:
                train_sessions.append(os.path.join(root_path,subject, session))
        


    train_records = {}
    for c in classes:
        class_data = []
        for session in train_sessions:
            data = np.load(os.path.join(session,c+post_fix+'.npy'),allow_pickle=True)
            if data.shape[0] != 0:
                class_data.append(data)
            #else:
            #    print(f"No data available for train for class {c}")
        
        train_records[c] = np.concatenate(class_data)
    print(f"{len(train_sessions)} sessions loaded for training")


    val_records = {}
    for c in classes:
        class_data = []
        for session in val_sessions:
            data = np.load(os.path.join(session,c+post_fix+'.npy'),allow_pickle=True)
            if data.shape[0] != 0:
                class_data.append(data)
        if len(class_data) != 0:
            val_records[c] = np.concatenate(class_data)
        #else:
        #    print(f"No data available for validation for class {c}")

    print(f"{len(val_sessions)} sessions loaded for validation")





    n_channels = train_records["Rest"].shape[1]
    input_length = train_records["Rest"].shape[2]


    train_y = create_labels(train_records)
    train_X = np.concatenate((list(train_records.values())), axis=0)



    val_y = create_labels(val_records)
    val_X = np.concatenate((list(val_records.values())), axis=0)

    train_X = np.array(train_X).reshape(-1,n_channels,input_length)
    train_y = np.array(train_y)

    val_X = np.array(val_X).reshape(-1,n_channels,input_length)
    val_y = np.array(val_y)


    train_y = applyOneHot(train_y,len(classes))
    val_y = applyOneHot(val_y,len(classes))
    
    train_X, train_y = apply_augment(train_X, train_y)
    
    c = list(zip(train_X, train_y))
    random.seed(42)
    random.shuffle(c)
    train_X,train_y = zip(*c)
    train_X = np.array(train_X)
    train_y = np.array(train_y)

    model = get_model(train_X.shape[1:], len(classes))
    

    reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                                factor=0.5,
                                min_delta=0.001,
                                patience=2,
                                min_lr=5e-8,
                                verbose = 1)
                                
    opt = keras.optimizers.SGD(learning_rate=1e-4, momentum=0.9)
    model.compile(optimizer=opt,
            loss='categorical_crossentropy',
            metrics=['categorical_accuracy']
            )
    batch_size = 128
    history = model.fit(train_X,
                        train_y,
                        validation_data=(val_X, val_y),
                        batch_size=batch_size,
                        epochs=30,
                        shuffle=True,
                        callbacks = [reduce_lr]
                        )
    return evaluate_set(model, val_sessions, classes, post_fix, log = log)
